[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
reqwest = "0.12.5"
passkey = "0.2.0"
async-trait = "0.1"

tokio = { version = "1.39.2", features = ["full"] }
serde_json = "1.0.120"
url = "2.5.2"
base64 = "0.22.1"
